services:
  sponsorblocktv-web:
    build:
      context: .
    container_name: sponsorblocktv-web
    # Uncomment next line if you want to use auto discovery
    network_mode: host
    environment:
      SBTV_ENABLE_DOCS: true
      SBTV_DEBUG: true
      SBTV_API_PORT: 80
    restart: unless-stopped
    volumes:
      - sbtv_data:/app/data

volumes:
  sbtv_data: {}
