services:
  sponsorblocktv-web:
    build:
      context: .
    container_name: sponsorblocktv-web
    environment:
      SBTV_ENABLE_DOCS: true
    ports:
      - 80:8000
    restart: unless-stopped
    volumes:
      - sbtv_data:/app/data

volumes:
  sbtv_data: {}
